// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("GogoKit")]
[assembly: AssemblyCompanyAttribute("viagogo")]
[assembly: AssemblyCopyrightAttribute("Copyright viagogo 2017")]
[assembly: AssemblyVersionAttribute("0.30.0")]
[assembly: AssemblyFileVersionAttribute("0.30.0")]
[assembly: AssemblyInformationalVersionAttribute("0.30.0")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.30.0";
    }
}
