// <auto-generated/>
using System.Reflection;
using System.Runtime.InteropServices;

[assembly: AssemblyProductAttribute("GogoKit")]
[assembly: AssemblyCompanyAttribute("viagogo")]
[assembly: AssemblyCopyrightAttribute("Copyright viagogo 2016")]
[assembly: AssemblyVersionAttribute("0.26.1")]
[assembly: AssemblyFileVersionAttribute("0.26.1")]
[assembly: AssemblyInformationalVersionAttribute("0.26.1")]
[assembly: ComVisibleAttribute(false)]
namespace System {
    internal static class AssemblyVersionInformation {
        internal const string Version = "0.26.1";
    }
}
